version: "3"
services:
  bssm_portfolio:
    container_name: bssm_portfolio
    image: bssm_portfolio
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      [./application-live.yml:/application-live.yml]
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE=DATABASE
      - MYSQL_USER=USER
      - MYSQL_PASSWORD=PASSWORD

