spring:

  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none

decorator:
  datasource:
    p6spy:
      enable-logging: off