spring:
  config:
    activate:
      on-profile: dv
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://bssmh-dv.cnvz4bcel8w5.ap-northeast-2.rds.amazonaws.com:3306/bssmh
      username: qkrjh0904
      password: akdlektm3#
      driver-class-name: com.mysql.cj.jdbc.Driver