spring:
  datasource:
    hikari:
      jdbc-url: ${bssmh-portfolio.spring.datasource.url}
      username: ${bssmh-portfolio.spring.datasource.username}
      password: ${bssmh-portfolio.spring.datasource.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            scope:
              - profile
              - email
          naver:
            client-id: ${oauth2.naver.id}
            client-secret: ${oauth2.naver.secret}
            scope:
              - profile
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${oauth2.naver.redirect-uri}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none

decorator:
  datasource:
    p6spy:
      enable-logging: off

