spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://bssmh-dv.cnvz4bcel8w5.ap-northeast-2.rds.amazonaws.com:3306
      username: qkrjh0904
      password: akdlektm3#
      driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope:
              - profile
              - email
              -
          naver:
            client-id: id
            client-secret: secret
            scope:
              - profile
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: uri
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none

decorator:
  datasource:
    p6spy:
      enable-logging: off

