spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: ${bssmh-portfolio.spring.datasource.url}
      username: ${bssmh-portfolio.spring.datasource.username}
      password: ${bssmh-portfolio.spring.datasource.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth:
      bsm:
        client-id: ${oauth.bsm.id}
        client-secret: ${oauth.bsm.secret}
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            scope:
              - profile
              - email
          kakao:
            client-id: ${oauth2.kakao.id}
            redirect-uri: ${oauth2.kakao.redirect-uri}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - birthday
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

decorator:
  datasource:
    p6spy:
      enable-logging: on
      multiline: true

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${bssmh-portfolio.aws.s3.access-key}
      secret-key: ${bssmh-portfolio.aws.s3.secret-key}

bssmh:
  s3:
    bucket-name: ${bssmh-portfolio.aws.s3.bucket-name}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

